server:
  port: 9000
spring:
  application:
    name: xdemo-auth
    version: v1.0
    description: demo系统用户权限服务
    profiles:
      active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/xdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 用户名
    password: 密码
  redis:
    # Redis 数据库索引（默认为 0）
    database: 0
    host: redis ip
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password: 密码
    # springboot 2.0 redis默认客户端已换成lettuce
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    timeout: 5000

nature:
  restApi:
    enabled: true

logging:
  level:
    com.xdemo.auth: debug

mybatis:
  #mapper配置文件
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.xdemo.auth.Repository
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
